//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('DailyEarnings')
export class DailyEarningsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('date', { nullable: true })
  earningsDate: Date;

  @Column('integer', { nullable: true })
  userId: number;

  @Column('integer', { nullable: true })
  machineId: number;

  @Column('real', { nullable: true })
  amountEarned: number;

  @Column('integer', { nullable: true })
  investmentId: number;
}
