//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Investments')
export class InvestmentsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  userId: number;

  @Column('integer', { nullable: true })
  machineId: number;

  @Column('date', { nullable: true })
  investmentDate: Date;

  @Column('real', { nullable: true })
  amountInvested: number;

  @Column('text', { nullable: true })
  investmentStatus: string;
}
