//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Machines')
export class MachinesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  machineName: string;

  @Column('real', { nullable: true })
  investmentCost: number;

  @Column('real', { nullable: true })
  dailyIncome: number;

  @Column('integer', { nullable: true })
  duration: number;

  @Column('real', { nullable: true })
  totalReturn: number;
}
