//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const DailyEarningsTitle = () => {
  const record = useRecordContext();
  return <span>DailyEarnings {record ? `"${record.earningsDate}"` : ''}</span>;
};

export const DailyEarningsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <DateField source="earningsDate" />
      <ReferenceField source="userId" reference="Users" />
      <ReferenceField source="machineId" reference="Machines" />
      <NumberField source="amountEarned" />
      <ReferenceField source="investmentId" reference="Investments" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const DailyEarningsEdit = () => (
  <Edit title={<DailyEarningsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <DateInput source="earningsDate" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="userId" reference="Users" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="machineId" reference="Machines" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="amountEarned" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="investmentId" reference="Investments" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const DailyEarningsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <DateInput source="earningsDate" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="userId" reference="Users" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="machineId" reference="Machines" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="amountEarned" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="investmentId" reference="Investments" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  <ReferenceInput source="userId" label="userId" reference="Users" alwaysOn />,
  <ReferenceInput
    source="machineId"
    label="machineId"
    reference="Machines"
    alwaysOn
  />,
  ,
  <ReferenceInput
    source="investmentId"
    label="investmentId"
    reference="Investments"
    alwaysOn
  />,
];
